### ISSUE TITLE
Widget not displaying song info and album artwork

### ISSUE THREAD

**Issue by chriscolomb** [topik/google-youtube-music-obs-widget#1]
![image](https://user-images.githubusercontent.com/68606773/92807607-ffa8a180-f3f5-11ea-8b85-16ffa1d3e91e.png)
This is with my own uploaded music. I cannot seem to fix it, even when I restart both the Stremlabs OBS and GMDMP.

**Comment by topik** [comment]
It doesn't work only for your own music uploaded to Google Music? Are you using Google Music or YT Music player?

**Comment by chriscolomb** [comment]
I forgot to mention I am using macOS. 

I've uploaded the m4a song to both Google and YouTube Music. Both platforms displayed the same blank widget.

**Comment by chriscolomb** [comment]
The problem fixed itself! I am sorry to cause any inconvenience. I believe the audio was not fully processed within Google Music, leading it to now show its metadata.
